### ISSUE TITLE
Conflict Display UI Bug

### ISSUE THREAD

**Issue by alexothomson** [CourseScheduler/scheduler-legacy#14]
Conflicts take up the rest of the day that the conflict takes place in the UI. Looks like maybe an end time isn't being set appropriately or something has changed in the UI libraries since the jump to Java 8.

Running on Java 8 x64.
![conflict display ui bug](https://cloud.githubusercontent.com/assets/4649212/5385884/80fa175e-8094-11e4-898f-2d12e273fd40.png)

**Comment by mikereinhold** [comment]
Fixed in 4.12.7
